[env]
platform = atmelmegaavr
board = AVR32DU28
;platform_packages = platformio/toolchain-atmelavr@^3.70300.220127

; Point directly to your custom toolchain folder
platform_packages = 
    toolchain-atmelavr@symlink:///home/nixigaj/dev/uni/enk/avr-gcc-new-build/avr-gcc-15.2.0-x64-linux

build_flags =
    -DUSB_EP_NUM=8
    -DUSB_MAX_ENDPOINTS=8

upload_protocol = custom

[env:usb]
upload_flags =
    -cserialupdi
    -pavr32du28
    -P/dev/ttyACM0
upload_command = "avrdude" $UPLOAD_FLAGS -U flash:w:$SOURCE:i

monitor_port = /dev/ttyACM1
monitor_speed = 19200

[env:erik]
upload_command =
    scp $SOURCE nixigaj@10.1.0.8:/tmp/firmware.hex
    ssh nixigaj@10.1.0.8 "avrdude -c serialupdi -p avr32du28 -P /dev/ttyAMA0 -b 115200 -U flash:w:/tmp/firmware.hex:i"

monitor_port = socket://10.1.0.8:4000
monitor_speed = 115200
